# Generated by Django 4.2.8 on 2025-10-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название рекламного носителя')),
                ('ad_type', models.CharField(choices=[('billboard', 'Билборд'), ('led_screen', 'LED-экран'), ('prismatron', 'Призматрон'), ('citylight', 'Ситилайт'), ('pillar', 'Столб')], max_length=20, verbose_name='Тип носителя')),
                ('address', models.TextField(verbose_name='Адрес размещения')),
                ('description', models.TextField(blank=True, verbose_name='Описание и характеристики')),
                ('rental_terms', models.TextField(blank=True, verbose_name='Условия и сроки аренды')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость аренды')),
                ('contact_info', models.TextField(blank=True, verbose_name='Контактная информация')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='adboards/', verbose_name='Фотография')),
                ('lat', models.FloatField(default=52.9994, verbose_name='Географическая широта')),
                ('lon', models.FloatField(default=78.6459, verbose_name='Географическая долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рекламный носитель',
                'verbose_name_plural': 'Рекламные носители',
                'ordering': ['ad_type', 'title'],
            },
        ),
    ]
