# Generated by Django 4.2.8 on 2025-10-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-описание')),
                ('category', models.CharField(choices=[('main', 'Главная'), ('about', 'О нас'), ('outdoor', 'Наружная реклама'), ('interior', 'Интерьерная реклама'), ('printing', 'Широкоформатная печать'), ('souvenirs', 'Сувенирная продукция'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Показывать в меню')),
                ('menu_order', models.PositiveIntegerField(default=0, verbose_name='Порядок в меню')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Триал', max_length=100, verbose_name='Название сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип')),
                ('phone', models.CharField(default='+7 (123) 456-78-90', max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(default='info@trial-agency.ru', max_length=100, verbose_name='Email')),
                ('address', models.TextField(default='г. Москва, ул. Рекламная, д. 123', verbose_name='Адрес')),
                ('working_hours', models.CharField(default='Пн-Пт: 9:00 - 18:00', max_length=100, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TextImageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(upload_to='text_images/', verbose_name='Изображение')),
                ('image_position', models.CharField(choices=[('left', 'Слева'), ('right', 'Справа')], default='right', max_length=10, verbose_name='Позиция изображения')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('external_link', models.CharField(blank=True, max_length=500, verbose_name='Внешняя ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.page', verbose_name='Ссылка на страницу сайта')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_image_sections', to='constructor.page')),
            ],
            options={
                'verbose_name': 'Текст с изображением',
                'verbose_name_plural': 'Тексты с изображением',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TextHtmlSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('html_content', models.TextField(help_text='Будет вставлен как есть', verbose_name='HTML-контент')),
                ('html_position', models.CharField(choices=[('left', 'Слева'), ('right', 'Справа')], default='right', max_length=10, verbose_name='Позиция HTML-контента')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('external_link', models.CharField(blank=True, max_length=500, verbose_name='Внешняя ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.page', verbose_name='Ссылка на страницу сайта')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_html_sections', to='constructor.page')),
            ],
            options={
                'verbose_name': 'Текст с HTML',
                'verbose_name_plural': 'Тексты с HTML',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SliderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay', models.BooleanField(default=True, verbose_name='Автопрокрутка')),
                ('autoplay_interval', models.PositiveIntegerField(default=5000, verbose_name='Интервал автопрокрутки (мс)')),
                ('show_controls', models.BooleanField(default=True, verbose_name='Показывать кнопки управления')),
                ('show_indicators', models.BooleanField(default=True, verbose_name='Показывать индикаторы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_sections', to='constructor.page')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Изображение')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('external_link', models.CharField(blank=True, max_length=500, verbose_name='Внешняя ссылка')),
                ('background_color', models.CharField(default='from-blue-800 to-blue-600', max_length=100, verbose_name='Градиент')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.page', verbose_name='Ссылка на страницу сайта')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='constructor.slidersection')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Наши услуги', max_length=200, verbose_name='Главный заголовок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_sections', to='constructor.page')),
            ],
            options={
                'verbose_name': 'Секция услуг',
                'verbose_name_plural': 'Секции услуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка')),
                ('icon_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет иконки')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('external_link', models.CharField(blank=True, max_length=500, verbose_name='Внешняя ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.page', verbose_name='Ссылка на страницу сайта')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='constructor.servicessection')),
            ],
            options={
                'verbose_name': 'Карточка услуги',
                'verbose_name_plural': 'Карточки услуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HtmlSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='HTML-код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='html_sections', to='constructor.page')),
            ],
            options={
                'verbose_name': 'HTML-секция',
                'verbose_name_plural': 'HTML-секции',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Фоновое изображение')),
                ('background_gradient', models.CharField(default='from-orange-800 to-orange-600', max_length=100, verbose_name='Градиент')),
                ('gradient_opacity', models.DecimalField(decimal_places=2, default=1.0, help_text='От 0.0 (прозрачный) до 1.0 (непрозрачный)', max_digits=3, verbose_name='Прозрачность градиента')),
                ('text_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет текста')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_sections', to='constructor.page')),
            ],
            options={
                'verbose_name': 'Герой-секция',
                'verbose_name_plural': 'Герой-секции',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_sections', to='constructor.page')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='constructor.gallerysection')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeaturesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Почему выбирают нас', max_length=200, verbose_name='Главный заголовок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_sections', to='constructor.page')),
            ],
            options={
                'verbose_name': 'Секция преимуществ',
                'verbose_name_plural': 'Секции преимуществ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка')),
                ('icon_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет иконки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='constructor.featuressection')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
    ]
