# Generated by Django 4.2.8 on 2025-10-30 23:14

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=ckeditor.fields.RichTextField(verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('main', 'Главная'), ('about', 'О нас'), ('outdoor', 'Наружная реклама'), ('interior', 'Интерьерная реклама'), ('printing', 'Широкоформатная печать'), ('souvenirs', 'Сувениры'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='texthtmlsection',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='textimagesection',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание'),
        ),
    ]
