# Generated by Django 4.2.8 on 2025-10-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_alter_feature_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок'),
        ),
    ]
